### ISSUE TITLE
wiki: Manual Content Installation fix

### ISSUE THREAD

**Issue by vgaming** [MustaphaTR/Romanovs-Vengeance#120]
Hi! The Manual Content Installation wiki can (should) be updated. https://github.com/MustaphaTR/Romanovs-Vengeance/wiki/Manual-Content-Installation

There is a typo. It says, for Linux, that the directory is:
```
On Linux: ~/.config/openra/content/ra2
```
Actually, the directory is:
```
On Linux: ~/.config/openra/Content/ra2
```
(The difference is that the "Content" word is capitalized.)

Testing done to confirm this: with the lowercase letters, the game would not proceed. When I've finally tried to capitalize that directory name, the game loaded and started working.

**Comment by MustaphaTR** [comment]
Thanks, fixed it.
