### ISSUE TITLE
Libya's Proper Flag

### ISSUE THREAD

**Issue by cahsobo** [MustaphaTR/Romanovs-Vengeance#124]
Hello, I'm new. Why is Libya's flag only a plain green?
Wouldn't it be better if the flag was changed properly?
![proper-libya](https://github.com/user-attachments/assets/a369b3e7-9192-4ab4-839c-3f54d7431fde)
![flags](https://github.com/user-attachments/assets/a366bf2a-1aaf-4090-9533-348e5c65dba2)

**Comment by cahsobo** [comment]
All you have to do is rename the flag's texture
![possible-changes](https://github.com/user-attachments/assets/777a4b36-d53e-4b33-b22a-72853b384419)

**Comment by GraionDilach** [comment]
Keep in mind that Libya had the green flag when it was aligned with the Soviets. https://en.wikipedia.org/wiki/Libya%E2%80%93Russia_relations#Soviet_era

The current tricolor is less applicable.

**Comment by cahsobo** [comment]
> Keep in mind that Libya had the green flag when it was aligned with the Soviets. https://en.wikipedia.org/wiki/Libya%E2%80%93Russia_relations#Soviet_era
> 
> The current tricolor is less applicable.

Ah.. I didn't know that. Thank you.
