### ISSUE TITLE
Can not run Romanovs Vengeance because I am missing Expansion Files and Music Files on Linux

### ISSUE THREAD

**Issue by brammittendorff** [MustaphaTR/Romanovs-Vengeance#15]
Hi there People of Romanovs Vengeance. We are so glad you made this mod. Yesterday we played https://github.com/OpenRA/ra2 But it is missing alot of features. So we saw this was the best Red Alert 2 mod so we want to try it. Today when we want to run Romanovs Vengeance it is asking for 4 things but we are missing 2:
Expansion Files
Expansion Music

This can be found on C&C The Ultimate Collection. We are a group that uses linux and mac os x, it is hard to mount (C&C The Ultimate Collection from origin). What is the correct way to do this? We already have the CD1 and CD2 of Red Alert and the DVD The First Decade mounted. How is it possible for Linux or Mac OS X users to run Romanovs Vengeance?

Kinds and regards,

Bram

**Comment by MustaphaTR** [comment]
Expansion Music should not be required but you need the YR files. We only have installer set up for those for origin, which i'm not even sure if it is working. Please manually copy ra2md.mix, langmd.mix and thememd.mix. I dunno how the CDs work, but i think you should be able to manually get the files off of it. We have the files uploaded somewhere, but i dunno if it would be a good idea to share here.

**Comment by GraionDilach** [comment]
If this is about TFD, then it has the files encapsualted within the InstallShield packages and I'm not sure how can they be extracted. The best method I could suggest is to run the installer through Wine and pray that it works..

**Comment by brammittendorff** [comment]
@MustaphaTR You are absolutely right we only need the following files:
```
ls -la ~/.openra/Content/ra2                                        ✔  10304  16:32:45
total 729892
drwxr-xr-x 2 bram bram      4096 feb 21 16:31 .
drwxrwxr-x 6 bram bram      4096 feb 20 17:16 ..
-rw-r--r-- 1 bram bram  84883510 feb 21 16:31 langmd.mix
-rw-r--r-- 1 bram bram  53105368 feb 20 17:16 language.mix
-rw-r--r-- 1 bram bram 204527696 feb 21 16:31 ra2md.mix
-rw-r--r-- 1 bram bram 281074192 feb 20 17:16 ra2.mix
-rw-r--r-- 1 bram bram  46859102 feb 21 16:31 thememd.mix
-rw-r--r-- 1 bram bram  76862662 feb 20 17:16 theme.mix
```

It is working thanks alot!

**Comment by brammittendorff** [comment]
So I think we can close this issue. Thanks!

**Comment by dannystaple** [comment]
Note for max users - you will need to put files in ~/Library/Application Support/OpenRA/Content/ra2
