### ISSUE TITLE
Psi commando C4 crash

### ISSUE THREAD

**Issue by tytannial** [MustaphaTR/Romanovs-Vengeance#2]
OpenRA engine version 810d59c
Red Alert 2: Romanov's Vengeance mod version 810d59c
on map 6ce9d39923dc223b452435a8a5ab6cdcde03bf98 (Paris Revisited by Westwood Studios).
Date: 2018-12-31 07:57:37Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: `ptroop` tried to mindcontrol `cawash07`, but the latter does not have the necessary trait!
   在 OpenRA.Mods.AS.Traits.MindController.Attacking(Actor self, Target target, Armament a, Barrel barrel)
   在 OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass11.<FireBarrel>b__10() 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Mods.Common\Traits\Armament.cs:行号 336
   在 OpenRA.Mods.Common.Traits.Armament.ScheduleDelayedAction(Int32 t, Action a) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Mods.Common\Traits\Armament.cs:行号 231
   在 OpenRA.Mods.Common.Traits.Armament.FireBarrel(Actor self, IFacing facing, Target target, Barrel barrel) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Mods.Common\Traits\Armament.cs:行号 321
   在 OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target target) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Mods.Common\Traits\Armament.cs:行号 269
   在 OpenRA.Mods.Common.Traits.AttackBase.DoAttack(Actor self, Target target, IEnumerable`1 armaments) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Mods.Common\Traits\Attack\AttackBase.cs:行号 128
   在 OpenRA.Mods.Common.Activities.Attack.TickAttack(Actor self, AttackFrontal attack) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Mods.Common\Activities\Attack.cs:行号 149
   在 OpenRA.Mods.Common.Activities.Attack.Tick(Actor self) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Mods.Common\Activities\Attack.cs:行号 66
   在 OpenRA.Activities.Activity.TickOuter(Actor self) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Game\Activities\Activity.cs:行号 174
   在 OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Game\Traits\ActivityUtils.cs:行号 37
   在 OpenRA.Actor.Tick() 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Game\Actor.cs:行号 145
   在 OpenRA.World.Tick() 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Game\World.cs:行号 362
   在 OpenRA.Game.InnerLogicTick(OrderManager orderManager) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Game\Game.cs:行号 616
   在 OpenRA.Game.LogicTick() 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Game\Game.cs:行号 640
   在 OpenRA.Game.Loop() 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Game\Game.cs:行号 770
   在 OpenRA.Game.Run() 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Game\Game.cs:行号 810
   在 OpenRA.Game.InitializeAndRun(String[] args) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Game\Game.cs:行号 256
   在 OpenRA.Program.Main(String[] args) 位置 d:\CSProject\Romanovs-Vengeance\engine\OpenRA.Game\Support\Program.cs:行号 37

**Comment by MustaphaTR** [comment]
Fixed by https://github.com/MustaphaTR/Romanovs-Vengeance/commit/cfa0f5f53e13dfb22d0e001d8612b4f212e3fbd6
