### ISSUE TITLE
Parabomb usage causes mouse pointer to disappear

### ISSUE THREAD

**Issue by devflame** [MustaphaTR/Romanovs-Vengeance#23]
Upon clicking where a parabomb (commander power) should take place, the mouse pointer disappears. It is still usable, just can't tell where clicking. Parabomb does not fire. Map does not matter.

Side note: When attempting to click on another power to use once this happens, the game crashes, See attached exception: 
[exception-2019-05-05T033503Z.log](https://github.com/MustaphaTR/Romanovs-Vengeance/files/3145101/exception-2019-05-05T033503Z.log)

**Comment by MustaphaTR** [comment]
Known issue that fix for it is PRed at upstream. For now try to use directional abilities properly, instead of simply clicking.

**Comment by MustaphaTR** [comment]
This should be fixed along with https://github.com/MustaphaTR/Romanovs-Vengeance/commit/e9b49e8e08fca96357d80e94191afea6b3a303fd
