### ISSUE TITLE
AppImage needs Mono

### ISSUE THREAD

**Issue by probonopd** [MustaphaTR/Romanovs-Vengeance#24]
> Romanovs Vengeance requires Mono 4.2 or greater and the cert-sync utility.
Please install Mono using your system package manager.

Mono needs to be bundled inside the AppImage. An AppImage may not have dependencies other than what comes with the target system (distribution) by default.

References:
* https://docs.appimage.org/introduction/concepts.html#do-not-depend-on-system-provided-resources
* https://github.com/AppImage/AppImageKit/wiki/Bundling-Mono-apps
* https://github.com/AppImage/appimage.github.io/pull/1561

**Comment by MustaphaTR** [comment]
Known issue. Recent changes on upstream broke a lot of stuff and we are doing engine updates as much as possible but SDK is not updated for those changes which is causing a lot of issues. Mono is why Travis have been failing too so we can't create installers.

**Comment by MustaphaTR** [comment]
This should be fixed now.

**Comment by GraionDilach** [comment]
This will only get fixed when https://github.com/OpenRA/OpenRAModSDK/pull/117 reaches RV. That hasn't happened yet.

**Comment by MustaphaTR** [comment]
That PR has been implemented to RV for a good while now.

**Comment by GraionDilach** [comment]
Weird choice to implement a draft PR. 🤷
