### ISSUE TITLE
Option to Disable Yuris Revenge

### ISSUE THREAD

**Issue by ibrokemypie** [MustaphaTR/Romanovs-Vengeance#4]
It would be really great to have an option to disable content from yuris revenge from matches, or from the game entirely.

**Comment by MustaphaTR** [comment]
Mod has/will have a complately different balancing compared to original including new units (we already have Flamethrower, Hind, Naval and Faction specific support powers etc.). Siege Chopper is T2, Soviet air units are built from Service Depot and so on. There is no point of disabling YR content.
