### ISSUE TITLE
VXL posture for RV by CastleJing

### ISSUE THREAD

**Issue by dnqbob** [MustaphaTR/Romanovs-Vengeance#42]
CastleJing really like ra2 mods on OpenRA, especially RV and AS. He is major on VXL posture so he want to pull some really cool fix on RV.

RV's missle projectile. No meme3 for ra2 modder to laugh at. (don't mind the shadow)
![GIF15](https://user-images.githubusercontent.com/13763394/77377795-2b37c100-6daf-11ea-9e45-e78c7c778680.gif)
![GIF16](https://user-images.githubusercontent.com/13763394/77377799-2d018480-6daf-11ea-8474-06307f1bd7ea.gif)
![GIF17](https://user-images.githubusercontent.com/13763394/77377801-2d9a1b00-6daf-11ea-8ccf-6839c5af8ece.gif)

As well as an aircraft posture introduced which is now only apply to scout drone.
![showcase](https://user-images.githubusercontent.com/13763394/77377853-62a66d80-6daf-11ea-88c2-a6e645bd69c2.gif)

In fact we have an [upstream pr](https://github.com/OpenRA/OpenRA/pull/17796) and pchote is working on to merge it and another branch about VXL. It may take long so CastleJing cannot wait to put this fix here. It drop the codes about VXL posture on ramp compared to [upstream pr](https://github.com/OpenRA/OpenRA/pull/17796) so it is much simpler and maintainable.

**Comment by MustaphaTR** [comment]
This is in now, for Rockets, Vehicle tilting and aircraft, tho Drone doesn't use it. So closing it.
