### ISSUE TITLE
make[1]: *** No rule to make target 'dependencies'.  Stop.

### ISSUE THREAD

**Issue by WillForan** [MustaphaTR/Romanovs-Vengeance#44]
when trying to `make` on linux

```
make[1]: Entering directory src/Romanovs-Vengeance/engine'
make[1]: *** No rule to make target 'dependencies'.  Stop.
make[1]: Leaving directory 'src/Romanovs-Vengeance/engine'
make: *** [Makefile:107: engine-dependencies] Error 2
```

engine/Makefile does have a `install-dependencies` target. but no `dependencies`.

**Comment by MustaphaTR** [comment]
The lastest engine update broke the building on Linux, i haven't checked yet but i'm aware of it as Travis fails too.

**Comment by MustaphaTR** [comment]
Should be working now.

**Comment by WillForan** [comment]
Fast turnover! Sorry I didn't see the Travis already had this covered
