### ISSUE TITLE
Red stripes in the left build palette row

### ISSUE THREAD

**Issue by Mailaender** [MustaphaTR/Romanovs-Vengeance#46]
![image](https://user-images.githubusercontent.com/756669/80509609-f0124a00-8979-11ea-9ed7-3ef0f14dd7e7.png)

**Comment by umLu** [comment]
Happens to me too

![image](https://user-images.githubusercontent.com/7364385/84215644-41474a80-aa9d-11ea-88a9-609d3f2fd969.png)
