### ISSUE TITLE
MiniYaml files missing final newlines

### ISSUE THREAD

**Issue by Phrohdoh** [MustaphaTR/Romanovs-Vengeance#53]
The following files are missing final newlines (per `.editorconfig` as of 3222c4625fde07ea8957249b88c51ea34b7097ef):
- [x] `mods/rv/installer/origin.yaml`
- [x] `mods/rv/installer/ra2.yaml`
- [x] `mods/rv/installer/origin-yr.yaml`
- [x] `mods/rv/languages/vxl2shp/model-sequences.yaml`
- [x] `mods/rv/maps/vxl2shp/model-sequences.yaml`

**Comment by MustaphaTR** [comment]
Thanks, fixed in https://github.com/MustaphaTR/Romanovs-Vengeance/commit/a6998c33015ba71fc61ed72a81be594641982440
