### ISSUE TITLE
Crash after building Weatherstorm device.(Plus some in logs).

### ISSUE THREAD

**Issue by Coldfusionstorm** [MustaphaTR/Romanovs-Vengeance#56]
Some additional notes.
General stutter
Started from multiplayer menu.
i started as Sovijet (random).
i started out with capturing the soviet CY right to me and then the Allied CY left for me. (i assume the map name is in the logs)

[perf.log](https://github.com/MustaphaTR/Romanovs-Vengeance/files/5477668/perf.log)
[sound.log](https://github.com/MustaphaTR/Romanovs-Vengeance/files/5477669/sound.log)
[server.log](https://github.com/MustaphaTR/Romanovs-Vengeance/files/5477670/server.log)
[nat.log](https://github.com/MustaphaTR/Romanovs-Vengeance/files/5477671/nat.log)
[client.log](https://github.com/MustaphaTR/Romanovs-Vengeance/files/5477672/client.log)
[debug.log](https://github.com/MustaphaTR/Romanovs-Vengeance/files/5477673/debug.log)
[exception-2020-11-02T194106Z.log](https://github.com/MustaphaTR/Romanovs-Vengeance/files/5477674/exception-2020-11-02T194106Z.log)

**Comment by MustaphaTR** [comment]
This is fixed by https://github.com/MustaphaTR/Romanovs-Vengeance/commit/6fcf7b2438c07034d2f3f2aec17a49cba8845977
