### ISSUE TITLE
Installing Red Alert 2 from Origin on MacOs

### ISSUE THREAD

**Issue by figassss** [MustaphaTR/Romanovs-Vengeance#65]
Good afternoon
I´m sorry if this question have already been made but im having so much difficult in this.
I have a windows 10 pc and my girl have Mac Os. I installed the game from Origin on my windows pc and worked like a charm because the installer of open ra playtest-20200805 detected the game and installed sucessfully,
The problem is since the game of origin dont work on Macos cant really install it and cant play on Mac.
I tried to search online and even tried to send some files from my game to my girl but cant seem to work.
Can pleeeease some 1 explain to me how is it possible and how can i make game working on Mac ? Tell me like im really dumb haha really need some help. Thanks a lot in advance =)

**Comment by MustaphaTR** [comment]
I already answered you on Discord, so i guess this can be closed.

**Comment by sunjianan9900** [comment]
hey I Found nothing on discord
only one hash tag here
![image](https://user-images.githubusercontent.com/10936316/133712759-e8f3d5cb-7a7f-4c8b-8037-ee4ef777981e.png)

**Comment by sunjianan9900** [comment]
https://discord.gg/4zKbDxvDNM
  And This link is disable

**Comment by MustaphaTR** [comment]
We have merged Romanov's Vengeance and Shattered Paradise Discord servers some time ago. Here's a link for it: https://discord.com/invite/hk428Wk Seems like i haven't updated the discord links on the wiki here, i'll do it.
