### ISSUE TITLE
Strange "debug" messages during multiplayer game.

### ISSUE THREAD

**Issue by ssnakee2** [MustaphaTR/Romanovs-Vengeance#7]
During a game with 3 players and 3 bots, messages kept appearing in the same style of the debug notification, saying something along the lines of "Debug: client #5 (an ai) used (i don't remember the rest)". These messages were very common, repeating often when approaching oil derricks, though I am not sure there is a corralation.
I do not have much info (I cannot get it to happen again), and my memory is not that good.

Sorry about the missing info; I will reply with the exact message if it occurs again.

Build:
e9e9907

**Comment by MustaphaTR** [comment]
Did you mess with the advanced options, there is a checkbox that opens AI debug messages.

**Comment by ssnakee2** [comment]
That would make sense. They started around the time the AI's used yuri clones and stole our units.
But they occurred soo much, like you would get one, followed by at least 20 in the space of 2 seconds.

And no we didn't have AI debug on.

**Comment by ssnakee2** [comment]
It is possible that when we turned off debug cheats the host (ibrokemypie) also pressed debug ai messages. This was also the same game we crashed with V3's. (It happened when i launched like 7 of them at a conscript) They were on different angles so maybe one of the angles when the unit's projectile is drawn crashes it? idk though don't listen to me I can barely make a unity thing that's not terrible.

**Comment by MustaphaTR** [comment]
That's not an AI message, it appers normally and for players too. AI probably gets it more often because it can give orders more often than a real person.

Also AI dsbug messages is not a debug cheat, it is advances setting, can be set per layer.
