### ISSUE TITLE
Arch/Manjaro Linux 20 Nov 2021 - net framework updated to 6.0.0 rather than 5.0.0

### ISSUE THREAD

**Issue by theodoreOnzGit** [MustaphaTR/Romanovs-Vengeance#76]
I just ran an sudo pamac update for manjaro (arch) linux. 

i'm on RV using the dev branch

This is what i got:

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=manjaro-x64

Could the code somehow accept 6.0.0? Since it is more updated as well..

**Comment by LinuxDonald** [comment]
This can be closed. Net 6 is now in Manajaro/ArchLinux and compile works.
