### ISSUE TITLE
Massive slowdowns in AI games.

### ISSUE THREAD

**Issue by GraionDilach** [MustaphaTR/Romanovs-Vengeance#78]
Doesn't seem to be pathfinding-related, but around T3 progression, something can literally cuts gamespeed to half. My Ryzen 3600x goes from 75 frames to 30 in one point during a 3v3 AI observer match and I have even seen this going down to a constant 5 FPS. Can't provide debug info much because it seems the game no longer generates perf.log(?).

Shattered Paradise is not affected, 3v3 AI lategame SP stays around 50 FPS here.

**Comment by MustaphaTR** [comment]
It is the Psychic Beacon, i really need to rework it but couldn't get around doing it yet. The code for the range limit is working wrong way around (units are checking for the beacon, instead of beacons checking for units).

**Comment by GraionDilach** [comment]
Oh, this is probably https://github.com/MustaphaTR/OpenRA/commit/c569090d0c9f246f70e4bb3c6ff50773d8dae291 then.

I don't think you should have loaded range into the global system but use a duplicate GpsDotAS (RangedGpsDot) against a RangedGps trait which can use a ProximityTrigger (to cache the actors), otherwise you won't have perf at all, yeah.

**Comment by MustaphaTR** [comment]
Fixed by https://github.com/MustaphaTR/Romanovs-Vengeance/commit/3e43011c8584f2391f2d2a3f4fa02628e7dd779b (and the relevant engine commit).
