### ISSUE TITLE
Unit shadows Rendered Incorrectly on bridges

### ISSUE THREAD

**Issue by ssnakee2** [MustaphaTR/Romanovs-Vengeance#8]
While testing out some stuff with tanks, I found that the game seems to treat them like they are flying when on bridges, or maybe it is the shadow cast onto the water being on a layer above the bridge?
Anyway, I have a screenshot to explain better.

<img width="1440" alt="screen shot 2019-01-14 at 3 31 40 pm" src="https://user-images.githubusercontent.com/35243139/51096654-29b95300-1812-11e9-8b38-bc6c3b8cd9b9.png">

Build: e9e9907

**Comment by MustaphaTR** [comment]
Known issue, which should probably be reported to upstream as no thing much i can do specifically for RV. This should be affecting TS mod at upstream.

**Comment by ssnakee2** [comment]
Ah ok. So engine issue with OpenRA.
